#!/usr/bin/with-contenv bash

cd /app

export PATH="/app/.venv/bin:$PATH"
export PYTHONDONTWRITEBYTECODE=1
export PYTHONUNBUFFERED=1

LOG_LEVEL="${LOG_LEVEL:-info}"

API_PORT="${API_PORT:-8000}"

WORKERS="${API_WORKERS:-4}"
exec s6-setuidgid abc /app/.venv/bin/uvicorn api.main:app_factory \
    --factory \
    --host 0.0.0.0 \
    --port "${API_PORT}" \
    --log-level "${LOG_LEVEL}" \
    --workers "${WORKERS}"
